# Generated by Django 4.2.1 on 2023-05-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting_app', '0002_alter_voter_options_alter_voter_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='flag_bearer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_voting_app.voter'),
        ),
    ]
