# Generated by Django 4.2.1 on 2023-05-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting_app', '0003_alter_party_flag_bearer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='flag_bearer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_voting_app.voter', unique=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_voting_app.voter', unique=True),
        ),
    ]
