# Generated by Django 4.2.1 on 2023-05-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_voting_app', '0004_alter_party_flag_bearer_alter_poll_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='acronym',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
